[package]
version = "0.0.1"
authors = [
  "nickray <n@stalder.io>",
]
description = "Peripheral access API for lpc55s6x microcontrollers"
documentation = "https://docs.rs/lpc55s6x-pac"
keywords = ["no-std", "cortex-m", "nxp", "lpc", "svd2rust"]
license = "MIT OR Apache-2.0"
name = "lpc55s6x-pac"
repository = "https://github.com/nickray/lpc55s6x-pac"
edition = "2018"

[dependencies]
bare-metal = "0.2.4"
vcell = "0.1"
cortex-m = ">= 0.5.8, < 0.7"

[dependencies.cortex-m-rt]
optional = true
version = "0.6.8"

[features]
rt = ["cortex-m-rt/device"]
